[project]
name = "claude-excuse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.61.0",
    "fastapi>=0.116.1",
    "uvicorn>=0.35.0",
]
